#!/usr/bin/env sh

check_dependencies() {
  if ! [ -x "$(command -v conda)" ]; then
    echo 'You need conda installed on your system in order to install required dependencies.' >&2
    exit 1
  fi
}

check_dependencies

# You may have to change this line to anaconda or another path.
# Make sure those exist. If you are unsure how to do this, but have some kind of conda installed
# just copy commands from line 17 till the end into your shell
[ -f /opt/miniconda3/etc/profile.d/conda.sh ] && source /opt/miniconda3/etc/profile.d/conda.sh

conda create -y --name spatial-networks
conda activate spatial-networks
conda install -y pip

pip install -r requirements.txt
# DVC for reproducibility, maintained well under conda
conda install -y -c conda-forge dvc
