#!/usr/bin/env bash

check_dependencies() {
  if ! [ -x "$(command -v dvc)" ]; then
    echo 'To create reproducible experiment you need DVC. Install conda dependencies from /environment.yml.' >&2
    exit 1
  fi
}

sticker() {
  delim=$1 # join delimiter
  shift
  oldIFS=$IFS # save IFS, the field separator
  IFS=$delim
  result="$*"
  IFS=$oldIFS # restore IFS
  echo "$result"
}

check_dependencies

EXPERIMENTS_PATH="../experiments"
EXPERIMENT_SPECIFIC=$(sticker "_" "$@")
PLOT_FILE="$EXPERIMENTS_PATH/plot_$EXPERIMENT_SPECIFIC.dvc"

dvc repro "$PLOT_FILE"
